// src/app/layout.jsx
import React from 'react'

import { Inter } from "next/font/google";
import "../styles/globals.css"; // Ensure global styles are applied
import Footer from "../app/components/footer"; // Import the Footer component

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <main>{children}</main> {/* Render the child pages here */}
        <Footer /> {/* Include the Footer component here */}

      </body>
    </html>
  );
}
